# Generated by Django 5.2.7 on 2025-10-20 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('specialty', models.CharField(help_text='ej: Barbero, Educador, Consultor', max_length=80, verbose_name='Especialidad')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='professionals/', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Servicio')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='Duración (minutos)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='agenda.professional')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(verbose_name='Hora fin')),
                ('max_clients', models.PositiveSmallIntegerField(default=1, verbose_name='Capacidad máxima')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='agenda.professional')),
            ],
            options={
                'unique_together': {('professional', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120, verbose_name='Nombre cliente')),
                ('client_phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.service')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='agenda.shift')),
            ],
        ),
    ]
